crdschurch/crds-styleguide

apache_site.conf
This PR adds a rewrite rule via Apache's mod_rewrite module to proxy any request for non-physical files to index.html. Once merged and deployed to INT, this should resolve the direct routing issue identified by [DE2639](https://rally1.rallydev.com/#/66096127196d/detail/defect/87023235356).
=> DE2639 Routing

src/app/ui-components/buttons/buttons.component.ts
This resolves the defect identified in [DE2685](https://rally1.rallydev.com/#/66096127196d/detail/defect/88073799064). 
I chose to handle in this manner (vs. using ng event handlers on the individual elements) because I don't want to clutter the implementation examples with irrelevant business logic. Let me know if you have any questions.
=> DE2685 Buttons

src/styles/_forms.scss
Fix focus border style on example input field. Uses the same focus style as `crds-styles`
Corresponds to `crds-styles/defect/DE2728-border-width`
=> DE2728 - Border width

src/app/ui-components/buttons/groups/groups.component.html
Remove active class from code examples and warning alert box related to the active class. Creates unnecessary confusion.
Corresponds with `crds-styles development` branch
=> DE2693 - Button groups not active in all browsers

src/app/ui-components/forms/forms.component.html, src/app/ui-components/typography/typefaces/typefaces.component.html
Remove dead link to alert section from forms and fix styling for link in warning-alert.
Corresponds with crds-styles `feature/US6543-separate-alert-section`
=> US6543 - Separate alert section

src/app/shared/content-block/content.service.ts
Cast apiUrl as string due to TeamCity build inconsistency.
=> DEXXXX Build Problems

src/app/ui-components/tables/tables.component.html
@tcmacdonald Per Brian's request, tables have been renamed with more generic classes and lean more on utility classes to achieve their looks.
Corresponds with `crds-styles/feature/US6287-tables`
=> US6287 - Tables

src/app/ui-components/forms/form-states/form-states.component.html
@tcmacdonald I added the `.ng-touched` class to example code and add more instruction to how the invalid state works with this class.
Corresponds with crdschurch/crds-styles#39
=> US6263 - Forms

src/app/app.component.ts
Radio buttons and checkboxes weren't behaving correctly (wouldn't select/deselect options). Rewriting a click event function so it only effects buttons and links.
Corresponds with `crds-styles/development`
=> DE2815 - Checkboxes and radio buttons busted

src/app/ui-components/forms/form-states/form-states.component.html
Addressing Brian's concerns on form field validation:
1. Implement valid/invalid `:focus` state, see Bootstrap [example](http://getbootstrap.com/css/#forms-control-validation)
2. Simplify invalid state
3. Validation should mimic embed in that it checks the input once a user clicks off the field
Corresponds with crdschurch/crds-styles#60
=> DE2895 - Invoke error states

src/app/ui-components/forms/form-groups/groups.component.html
> It looks like the way we've overwritten the default bootrap inputs causes "input-lg" class to not work.
The amount field should be larger (to match prod design) in embed once the above issue is resolved.
Corresponds with crdschurch/crds-styles#59
Corresponds with crdschurch/crds-embed#255
=> DE2897 - Input lg

src/app/ui-components/forms/form-groups/groups.component.html
> Update the vertical button group examples to display icons based on the current selection.
Corresponds with crds-styles/development
=> US6463 - Vertical btn svgs in ddk

package.json, src/app/ui-components/forms/form-groups/groups.component.html
Finder styling issue move buttons and elements off screen
Map View
Searchbar reflows
Getting started and my Pin buttons cause scroll bars for screen, Also move offscreen on mobile when rotating screen
I updated the custom input fields (on form-groups)
Corresponds with defect/DE2988-finder-component-styling-issues of `crds-styles`, `crds-styleguide`, `crds-finder`, `crds-embed`
=> DE2988 - Finder component styling issues

src/app/ui-components/icons/colors/colors.component.html, src/app/ui-components/icons/inline-svg/inline-svg.component.html, src/app/ui-components/icons/resize-svg/resize-svg.component.html
I updated the example code blocks for SVGs to include the `xlink:` prefix. Also added an info box explaining why this is important for Safari/iOS
Corresponds with crds-styles/development and crdschurch/crds-connect#105
----------
the magnifying glass icon in the search submit button does not show in safari on ios and mac 
=> DE3028 - Search icon missing in Safari/iOS

src/app/ui-components/buttons/styles/styles.component.html
Toggle button look/behaviour is still being decided on. Being pulled out of DDK/`crds-styles` and moved into `crds-connect` as a connect-specific style until further defined.
Corresponds with:
crdschurch/crds-styles#101
crdschurch/crds-connect#252
=> US7849 - Toggle btn DDK

src/app/app.component.ts
Scroll to the top of the page after navigating to a new page.
---
when you had made this change
" in the fourt bullet (shown below) link the words "Responsive Web Design" to https://design-int.crossroads.net/designers/getting-started/responsive-web-design"
the link is working, but i would expect it to be at the top of the Responsive Web Design page, currently it goes somewhere at the bottom of the page.
---
No corresponding pull requests.
=> DE3384 - Link to Page Top

config/webpack.common.js, src/examples/datepicker/index.html, src/examples/map/index.html, src/examples/toastr/index.html
Use simple string replacement solution for injecting crds-styles into example blocks.
Previously I was hitting an error during a production build because the DOMParser did not like the attributes being used on some of the elements within these examples. This will continue to be an issue as example apps get more complicated.
This solution isn't awesome. It assumes an `index.html` file that has a reference to `/app.css`, and anywhere it finds that reference, it replaces it. This would ideally be more flexible down the road, but for now we are out to find a way to get these examples working in int.
=> DE3546 - Example Blocks

src/app/ui-components/countdown/countdown.component.html
Add updated countdown markup to CR homepage. Modifying the markup to more accurately reflect the correct implementation.
Created a new component on CMS called `countdown_test` to test new layout. Will need to be moved to `countdown` content-block after code freeze (I think? 🤔).
Corresponds with crdschurch/crds-styles#137
=> US8558 - Homepage countdown bar

src/app/ui-components/cards/types/types.component.html
Remove the .text-muted class from card examples. This is redundant now that this class sets a default color of light-gray.
Corresponds with crdschurch/crds-styles#138
---
Feedback from Rob: 
*Cards*
- All `.card { margin-bottom: 1rem; }` `.card-block { font-size: 14px;` }
- Default, h5 `color: $cr-gray-light`
- Card w/ Caption label  `.card-caption:before { top: -30px; font-size: 13px;}`
=> US8773 - Card style tweaks

src/app/ui-components/jumbotrons/jumbotrons.component.html, src/examples/jumbotron-video/index.html, src/examples/jumbotron-video/video.js
- `.container .jumbotron, .container-fluid .jumbotron { border-radius: 0; }`
- `.jumbotron { padding-top: 150px; padding-bottom: 150px; }` <-- (100px @ mobile) 
- `.jumbotron .small-heading { font-size: .85rem; line-height: 1; opacity: .8;}`
- `.jumbotron .title { margin: 1rem 0; }`
- `.jumbotron a.btn { margin: 1rem .25rem 0; }`
- Padding helper: Default to 48px. Then small (32px), large (80px), xlarge (112px). 
- Move loading spinner to top right corner of container; make smaller
- support different video for bkg & button
- both video links should be editable via CMS
- add close btn while video is playing 
- automatically go back to jumbotron once video ends
---
Corresponds with crdschurch/crds-styles#141 and crdschurch/crds-maestro#150.
=> US8725 - Jumbotron Revisions

src/examples/video-modals/video-modal.component.html
Make button on video modals close the modal.
This defect also applies to int, but can be viewed on int without any local changes (assuming cache has cleared since I made the last markup change).
=> DE3687 - Modal Close

src/app/ui-components/ui-components.module.ts, src/app/ui-components/ui-routing.module.ts, src/app/ui-components/utilities/buttons/buttons.component.html, src/app/ui-components/utilities/buttons/buttons.component.spec.ts, src/app/ui-components/utilities/buttons/buttons.component.ts, src/app/ui-components/utilities/utilities.component.html, src/examples/datepicker/index.html, src/examples/jumbotron-video/index.html, src/examples/jumbotron-video/video.js, src/examples/map/index.html, src/examples/toastr/index.html, src/examples/video-modals/index.html
Given a developer viewing the DDK
When I view utility classes
Then i should see the .btn-block-mobile selector with a description of what it will do to help me make awesome buttons. 
Given a user viewing /connect
When I view a CTA throughout the application on mobile
Then it should be displayed 100% wide, block-level on my tiny screen
Given a user viewing /connect
When I view a CTA throughout the application on desktop
Then I should see inline-block elements that do not fill up 100% of my screen width. 
---
Corresponds with:
- crdschurch/crds-styles#142
- crdschurch/crds-maestro#151
- crdschurch/crds-connect#411
=> US8429 - Block Level Buttons

src/examples/video-modals/video-modal.component.html, src/examples/video-modals/video-modal.component.ts
Addresses:
> If I start playing video in modal and then stop the video (by clicking "X") in the upper right corner, video stops playing, but audio continues.
>
> That is the case in both - modal in DDK and Home Page (https://int.crossroads.net/homepage-logged-out) when I click Watch the Trailer button
---
Corresponds to crdschurch/crds-maestro#154
=> DE3707 - Stop Modal Audio

src/app/directives/icons/icons.service.ts
Add link icon to DDK.
Modify the group detail view such that the social icons appear outside of the expanded description field. User should not have to expand description to access the social icons to share the group. Defer to Rob for positioning as needed. 
Also we need to add a link icon so the user can copy the direct URL to the group.
Corresponds with crdschurch/crds-styles#180
Corresponds with crdschurch/crds-connect#540
=> US9342 - Social icons

src/app/ui-components/molecules/jumbotrons/jumbotrons.component.html, src/examples/jumbotron-bg-video/bg-video.js, src/examples/jumbotron-bg-video/index.html
Work that was completed in US9042 involved changing the video
implementation from YouTube iFrame API to native HTML video tag. This
work updates documentation / examples in the DDK to allow users to
reference Jumbotron Background Video implementation for use around other
parts of the website.
=> US9932 Update example for bg jumbotron video

src/app/services/linkable-header.service.ts
Don't process linkable header when header is inside an example
=> DE4564 - Font Scaling Linkable Headers

src/app/assets/logos/logos.component.html
Add expanded CR logo to logo section of DDK.
Testable on `/assets/logos` and `/designers/guidelines/logos`
Corresponding PR: crdschurch/crds-styles#243
=> DE4582 - DDK logo

src/app/app.component.spec.ts, src/app/app.module.ts, src/app/directives/theme-toggle-switch/theme-toggle-switch.component.ts, src/app/directives/theme-toggle-switch/theme-toggle-switch.service.ts, src/app/layout/header/header.component.spec.ts, src/app/shared/example/example.component.html, src/app/shared/example/example.component.spec.ts, src/app/shared/example/example.component.ts, src/app/ui-components/atoms/icons/inline-svg/inline-svg.component.spec.ts, src/app/ui-components/core/colors/backgrounds/backgrounds.component.spec.ts, src/app/ui-components/core/colors/text/text.component.spec.ts, src/examples/_shared/theme_toggler.js, src/examples/accordion/index.html, src/examples/button-dropdown/index.html, src/examples/card-deck-carousel/index.html, src/examples/card-deck-default/index.html, src/examples/charts/index.html, src/examples/datepicker/index.html, src/examples/jumbotron-bg-video/index.html, src/examples/jumbotron-inline-video/index.html, src/examples/map/index.html, src/examples/timepicker/index.html, src/examples/toastr/index.html, src/examples/tooltips/index.html, src/examples/video-modals/index.html, src/styles/_examples.scss, src/styles/_variables.scss
The primary focus of this defect was to support dark-theme toggling within interactive examples. I ended up finding a few other dark theme issues and fixed those along the way. All in all, in conjunction with crdschurch/crds-styles#271, this addresses:
- Style support for dark theme on accordions, panels, and striped tables
- Communicating the current theme to interactive examples and toggling to match
- Maintaining a dark theme within interactive examples when navigating to a new page
=> DE4830 - Dark Theme Interactive Examples

package-lock.json, src/app/layout/header/header.component.html, src/examples/modals/default-modal-form.component.html, src/examples/modals/default-modal-promo.component.html, src/examples/modals/default-modal.component.html, src/examples/modals/full-modal-form.component.html, src/examples/modals/full-modal.component.html, src/examples/modals/video-modal.component.html
Add the ability to click backdrop to close modals. Excludes full-screen modals because they're full-screen and don't have a backdrop to click.
No corresponding PRs.
=> US11789 - Modal

_assets/stylesheets/_global.scss, _includes/_header.html
Nav link for Designers is always blue, whether active or not.
Remove `.on` class and related styles. This feels like broken markup that got brought in from DDK-NG as the active states for nav are black, not blue. The `.on` class doesn't appear to do anything, as Bootstrap uses an `.open` class to determine active state.
=> Remove .on class and styles so active state matches PROD.

content-administrators/copy-voice.html, content-administrators/monetate-templates.html
Also fixes linkable sections on Monetate templates page
This page also is linked to the following crds-styles PR that was missed when the original story was merged:
https://github.com/crdschurch/crds-styles/pull/354
Because of submodules, the styles are reflected in Styleguide, but it won't be connected to the new version of crds-styles without being merged
=> DE6235 Fixes Active State on Content Admin Submenu

ui-components/molecules/tabs.html
Rewrites the vertical tab system to not collapse into a dropdown element, but to use its natural self, with the option to make use of BS' collapse feature. In addition, the collapse feature can be used within the tabs to create subnav lists that are hidden by default.
Feel free to check out the updated documentation and the [preview](https://deploy-preview-403--crds-styleguide.netlify.com/ui-components/molecules/tabs.html) for an example.
---
Corresponds to: crdschurch/crds-styles#374 and crdschurch/crds-media#513.
=> US16400 - Article Filter Accordion
