crdschurch/crds-styleguide

config/webpack.common.js
Update webpack config to copy Apache config.
=> DE2639 Routing

src/index.html
Update typekit script to keep it from being blocked by design-int.
=> DE2680 - Typekit Blocked

src/app/ui-components/colors/colors.component.html, src/styles/_colors.scss, src/styles/_global.scss
This PR addresses @bzmillerboy's comments by removing latin copy and implementing details on which colors override Bootstrap defaults.
=> US6369 Colors

src/app/ui-components/buttons/jumbotron/jumbotron.component.html
Remove Latin text from button jumbotron.
=> DE2690 - Disabled Outline Buttons

src/app/layout/header/header.component.html, src/app/ui-components/buttons/jumbotron/jumbotron.component.html, src/app/ui-components/colors/colors.component.html, src/app/ui-components/colors/overrides/overrides.component.html, src/app/ui-components/colors/overrides/overrides.component.ts, src/app/ui-components/colors/swatches/swatches.component.html, src/app/ui-components/colors/swatches/swatches.component.ts, src/app/ui-components/forms/forms.component.html, src/app/ui-components/forms/jumbotron/jumbotron.component.html, src/app/ui-components/typography/typefaces/typefaces.component.html, src/app/ui-components/ui-components.module.ts, src/app/ui-components/ui-routing.module.ts, src/styles/_colors.scss
Update the DDK & shared style package to reflect the most recent set of colors, Sass variables & Bootstrap overrides. 
https://www.dropbox.com/sh/yvhvaoixzg3tfgb/AADQ1K74XhYQ4FnExIoLap5la?dl=0&preview=colors-01-brand.png
Corresponds with branch crds-styleguide `feature/US6587-update-colors`
=> US6587 - Update colors

src/app/ui-components/colors/overrides/overrides.component.html
Update color overrides with correct hex values.
Corresponds to `crds-styles/development`
=> DE2745 - Hex values

src/app/shared/content-block/content.service.ts
Disable linter warnings for no-construct
=> DEXXXX Build Problems

src/app/ui-components/sign-in/sign-in.component.html
=> US6285 Sign In

src/app/ui-components/typography/typesetting/typesetting.component.spec.ts, src/app/ui-components/typography/typesetting/typesetting.component.ts
Prevent reload of page when clicking link within example blocks
=> DE2789 Link Examples

config/webpack.common.js
Remove reference to non-existent file. /cc @chris-branch
=> DEXXXX Apache Config

src/app/ui-components/icons/css-svg/css-svg.component.html, src/app/ui-components/icons/directory/directory.component.html, src/app/ui-components/icons/inline-svg/inline-svg.component.html
Create code examples for the new dollar sign SVG/CSS.
=> DE2838 - SVG dark theme

src/app/ui-components/buttons/styles/styles.component.html
A triad of PRs (if you will)... 
* crdschurch/crds-styles#55
* crdschurch/crds-embed#250
* crdschurch/crds-styleguide#64
=> DE2877 Outlined Buttons

src/app/ui-components/utilities/utilities.component.html
> There is too much margin around the pre-defined amount, the vertical rhythm is off. [Link](https://www.dropbox.com/s/3z18751xyb2vdfv/Screenshot%202017-03-03%2022.18.52.png?dl=0)
Corresponds with:
crdschurch/crds-styles#62
crdschurch/crds-embed#256
=> DE2896 - Reduce donation btn margins

config/webpack.common.js, src/app/directives/icons/icons.service.spec.ts, src/app/directives/icons/icons.service.ts, src/app/ui-components/forms/form-groups/groups.component.html, src/app/ui-components/icons/colors/colors.component.html, src/app/ui-components/icons/colors/colors.component.spec.ts, src/app/ui-components/icons/colors/colors.component.ts, src/app/ui-components/icons/css-svg/css-svg.component.html, src/app/ui-components/icons/css-svg/css-svg.component.spec.ts, src/app/ui-components/icons/css-svg/css-svg.component.ts, src/app/ui-components/icons/directory/directory.component.html, src/app/ui-components/icons/directory/directory.component.spec.ts, src/app/ui-components/icons/directory/directory.component.ts, src/app/ui-components/icons/icons.component.html, src/app/ui-components/icons/inline-svg/inline-svg.component.html, src/app/ui-components/icons/inline-svg/inline-svg.component.spec.ts, src/app/ui-components/icons/inline-svg/inline-svg.component.ts, src/app/ui-components/icons/resize-svg/resize-svg.component.html, src/app/ui-components/ui-components.module.ts, src/app/ui-components/ui-routing.module.ts
Update icon directory and use new SVG inline implementation.
=> DE2885 - Use Inline SVGs

src/app/ui-components/utilities/utilities.component.html
=> DE2904 Truncate Strings

package.json
Lock @types/core-js package to 0.9.36
=> DEXXXX Lock Dependencies

src/app/ui-components/forms/form-groups/groups.component.html, src/app/ui-components/icons/colors/colors.component.html, src/app/ui-components/icons/directory/directory.component.html, src/app/ui-components/icons/inline-svg/inline-svg.component.html, src/app/ui-components/icons/resize-svg/resize-svg.component.html
Remove unecessary attributes from use elements
=> DE2886 - Icon Colors

src/app/directives/theme-toggle-switch/theme-toggle-switch.component.ts, src/app/layout/header/header.component.html, src/app/ui-components/forms/form-groups/groups.component.html, src/app/ui-components/icons/colors/colors.component.html, src/app/ui-components/icons/directory/directory.component.html, src/app/ui-components/icons/inline-svg/inline-svg.component.html, src/app/ui-components/icons/resize-svg/resize-svg.component.html, src/header.ejs
Fix icons and header for mobile
=> US5154 - Header

src/app/directives/icons/icons.service.ts
Related to crdschurch/crds-styles#85
=> US7510 Leader Application Profile Page

src/app/ui-components/forms/form-groups/groups.component.html
As a designer/developer, I want to see guidance for input-group-btn in the DDK & crds-styles. 
---
I showed two examples here, so we could see a button with text and another with an icon. Not sure it's the best way to present, but wanted to show you two and we can adjust.
---
Works with the changes from crdschurch/crds-styles#87.
=> US7369 - Input Group Button

src/app/ui-components/forms/forms.component.html, src/app/ui-components/forms/search/search.component.html, src/app/ui-components/forms/search/search.component.spec.ts, src/app/ui-components/forms/search/search.component.ts, src/app/ui-components/ui-components.module.ts, src/app/ui-components/ui-routing.module.ts
Given a designer/developer
When I need to apply a search field to my crossroads application
Then I should find style direction for this within the DDK
=> US7471 - Search Bar

src/app/ui-components/buttons/groups/groups.component.html, src/app/ui-components/buttons/groups/groups.component.ts
Add support for vertical button groups
---
Connected to crdschurch/crds-styles#92 and crdschurch/crds-connect#202.
=> US7830 - Vertical Button Groups

src/app/ui-components/forms/form-groups/groups.component.html, src/app/ui-components/forms/search/search.component.html
Revert "Merge pull request #99 from crdschurch/feature/US7754-css-refactor-searchbar"
This reverts commit f954106902dc5c5ba5e181c57f0c47f9cc117221, reversing
changes made to a2f277ba24f78a65bf8404c3ea44ee11c0c715bb.
crdschurch/crds-styles#94
crdschurch/crds-connect#216
crdschurch/crds-styleguide#103
=> DE3270 Revert Search Bar

package.json
Lock version to 0.4.0
crdschurch/crds-styleguide#106
crdschurch/crds-connect#225
crdschurch/crds-maestro#46
=> US7883 CRDS Styles

src/app/ui-components/buttons/styles/styles.component.html
Document toggle button in DDK.
=> US7849 - Toggle Button

package.json
=> USXXXX - CRDS Styles Version

src/app/designers/getting-started/prototyping/prototyping.component.html, src/app/designers/guidelines/copy-voice/copy-voice.component.html, src/app/designers/guidelines/logos/logos.component.html, src/app/designers/guidelines/photography/photography.component.html, src/app/designers/guidelines/typography/typography.component.html, src/styles/_global.scss
Content remains hard coded here
1. https://design-int.crossroads.net/designers/guidelines/logos -- update mailto: link in "Have questions?" section to design@crossroads.net
2. https://design-int.crossroads.net/designers/guidelines/copy-voice - update the alert  "Note: All content should be approved by: ___________ before being published to the web." with Adam George
3. https://design-int.crossroads.net/designers/getting-started/prototyping - in the "Step 1: Get Sketch" link the phrase "Go get Sketch" to https://www.sketchapp.com
4. https://design-int.crossroads.net/designers/getting-started/prototyping - in the fourt bullet (shown below) link the words "Responsive Web Design" to https://design-int.crossroads.net/designers/getting-started/responsive-web-design
If you’re starting a new …
=> US8002 - Designers Copy Edits

package.json
Update crds-styles to latest version
=> US8050 Publish NPM Package

package.json
Update crds-ng2-content-block to latest version
=> US8043 Publish NPM Package

src/app/developers/intro/intro.component.html
=> US8001 Cleanup Developers Section

src/styles/_examples.scss, src/styles/_footer.scss, src/styles/_global.scss, src/styles/_header.scss
=> US8179 - DDK Dark theme

src/app/layout/header/header.component.html, src/app/ui-components/labels/labels.component.html, src/app/ui-components/labels/labels.component.spec.ts, src/app/ui-components/labels/labels.component.ts, src/app/ui-components/ui-components.module.ts, src/app/ui-components/ui-routing.module.ts
Given a designer or developer
When using the DDK
Then I should see atoms that represent the pill/labels similar to those found in Connect for HOST and ME users
---
No corresponding PRs.
=> Feature/US6917 - Labels

package.json
Update dependency to latest version
=> US8469 Update CRDS Styles

package.json
Update file so DDK uses current styles.
=> DEXXXX - Update crds-styles to use development branch.

src/app/ui-components/cards/types/types.component.html
Implement a feature card style based on cards component.
Corresponds with crdschurch/crds-styles#131
---
This is a featured card similar to how we're treating current series. This is a hero image, caption (pill), possibly description, tags, and CTA link.
Utilize existing atoms to create new molecule for feature card. 
=> US6294 - Feature card

src/app/ui-components/typography/typefaces/typefaces.component.html
Remove references to variables in /ui/typography/web-fonts
=> DE3560 DDK References

package.json
=> US8658 - CRDS Styles Version

src/app/layout/header/header.component.html, src/app/ui-components/countdown/countdown.component.html, src/app/ui-components/countdown/countdown.component.ts, src/app/ui-components/ui-components.module.ts, src/app/ui-components/ui-routing.module.ts
Add markup for the countdown component.
Corresponds with crdschurch/crds-styles#135
---
Add markup for countdown timer to DDK
Includes blue bar w/ countdown styles and styles for Watch Now btn
Does not include sticky header implementation
=> US8627 - Countdown to DDK

package.json
Updating crds-styles to point at the development branch.
=> US8627 - Update package

src/app/layout/header/header.component.html, src/app/ui-components/fauxdals/fauxdals.component.html, src/app/ui-components/fauxdals/fauxdals.component.spec.ts, src/app/ui-components/fauxdals/fauxdals.component.ts, src/app/ui-components/ui-components.module.ts, src/app/ui-components/ui-routing.module.ts, src/styles/_component-list.scss
Adding fauxdal example to DDK.
--- 
corresponds to 
- crdschurch/crds-styles#139
- crdschurch/crds-connect#405
- crdschurch/crds-maestro#148
=> US7828: Fauxdal Refactor

src/app/ui-components/cards/grid-layout/grid-layout.component.html
This PR updates the implementation details for card elements with information about helper classes.
Related to crdschurch/SS-CMS#355
Related to crdschurch/crds-maestro#146
Related to crdschurch/crds-styles#140
=> US8669 Feature Template

src/examples/map/index.html
Fix for:
> While loading maps example (https://design-int.crossroads.net/developers/maps) spinner is spinning off center: [Download Attachment](https://rally1.rallydev.com/slm/attachment/126802588012/maps%20spinner.gif)
=> DE3676 - Map Loading Spinner Position

src/app/directives/icons/icons.service.ts
Add thin close icon for searchbar.
Corresponds with crdschurch/crds-styles#145 and crdschurch/crds-connect#419
=> US8745 - Add close icon

src/app/ui-components/colors/backgrounds/backgrounds.component.html
Add new helper class for dark blue background.
Goes with crdschurch/crds-styles#154
=> DE3736 - Chat section edits

package.json
=> US8844 - Publish NPM Package

package.json
Point package.json to development branch of crds-styles.
=> DE3762 - Collection header font

src/app/ui-components/cards/grid-layout/grid-layout.component.html, src/app/ui-components/cards/types/types.component.html, src/examples/card-deck-carousel/index.html, src/examples/card-deck-default/index.html, src/header.ejs
Update imgix instances to reflect appropriate usage
=> US8916 Imgix References

package.json
=> US8992 - Publish NPM Package

package.json
=> DE3800 - Fail Gracefully

package-lock.json, src/app/ui-components/countdown/countdown.component.html
Edited example to include section which displays when a stream is live.
=> US9039: Add Live Section to DDK

src/examples/jumbotron-bg-video/bg-video.js
Add player option to remove annotations, fixing the suggested video box from showing up.
Corresponds with crdschurch/crds-maestro#182
---
jumbotron video displaying "suggested" videos in lower left corner
=> DE3838 - Suggested vid

src/app/directives/icons/icons.service.ts
Add new icon.
Corresponds with crdschurch/crds-styles#171
---
As a user visiting DDK
When visiting the icons section
Then I should see an icon called 'exclamation-circle' in the directory list.
=> US9154 - New icon

package.json, src/app/ui-components/forms/forms.component.html, src/app/ui-components/forms/timepicker/timepicker.component.html, src/app/ui-components/forms/timepicker/timepicker.component.ts, src/app/ui-components/ui-components.module.ts, src/app/ui-components/ui-routing.module.ts, src/examples/timepicker/component.ts, src/examples/timepicker/config.js, src/examples/timepicker/index.html, src/examples/timepicker/main.ts, src/examples/timepicker/manifest.json, src/examples/timepicker/module.ts
Given a designer/developer
When visiting the ui/forms section of DDK
Then I should find the timepicker with associated styles and implementation in the sidebar navigation
---
Corresponds with crdschurch/crds-styles#170.
=> US6546 - Timepicker to DDK

package.json
=> US9171 - NPM Package

package-lock.json, src/app/ui-components/forms/form-groups/groups.component.html
Given a designer/developer 
When implementing a btn form group on a Crds application
Then I should find implementation details for the updated btn group in the DDK with the vertical rule for indented/child options rather than the caret
Given a crds.net/groups user
When starting a group
Then I should see the updated btn form group implemented within any selections that have nested child options 
---
Corresponds to crdschurch/crds-connect#508 and crdschurch/crds-styles#173.
=> US9159 - Btn Indent Style

src/app/app.component.ts, src/app/ui-components/forms/search/search.component.html, src/index.html
Given a Groups user
When I view the Finder Group Tool
Then I should see a search bar that matches the approved design
---
Note there is some "graceful" degradation in IE 10/11 with the size of the button. I'd rather create a defect to address that specifically, but if you want that fixed here, can do.
---
Corresponds to crdschurch/crds-styles#182 and crdschurch/crds-connect#533.
=> US9300 - Search Bar Fixes

package.json
=> US9403 crds-styles

package.json
=> Update NPM Package

src/app/ui-components/cards/grid-layout/grid-layout.component.html, src/app/ui-components/cards/types/types.component.html, src/examples/card-deck-carousel/index.html, src/examples/card-deck-default/index.html
Given a Goonie
When appearing in the DDK
Then I should **unfortunately** be replaced with an image more on-brand for Crds
Given a Goonie
When considering if Chunk is alive
Then never say die
=> US8892 - Goonies Never Say Die

src/app/ui-components/forms/form-controls/form-controls.component.html
Update checkbox markup with work with new CSS.
Corresponds with crdschurch/crds-styles#196
=> UD9386 - New checkboxes

src/app/ui-components/forms/form-groups/groups.component.html
Fix this:
---
crdschurch/crds-styles#200
crdschurch/crds-connect#612
=> DE4124 - Button Text Overflow

src/app/ui-components/buttons/buttons.component.html, src/app/ui-components/buttons/placement/placement.component.ts, src/app/ui-components/ui-components.module.ts, src/app/ui-components/ui-routing.module.ts
Given a designer/developer working on apps for cr.net
When I need direction on how buttons should be aligned within the context of my app
Then I should find instructions for this within the DDK
=> US9481 - Add Button Usage Page

package.json
Update crds-styles to latest version.
=> US9573 Publish NPM Package

src/examples/jumbotron-bg-video/index.html, src/examples/jumbotron-inline-video/index.html, src/examples/video-modals/app.component.html
Skateboard cat's been "dealt" "with", if you know what I mean.
=> DE4165 - Kill skateboard cat

src/app/developers/getting-started/coding-style/coding-style.component.html
Implement new information related to data-automation-id conventions.
Related to crdschurch/SS-CMS#414
=> US9877 Data Automation Ids

package-lock.json, src/app/ui-components/atoms/icons/inline-svg/inline-svg.component.html
=> US9695 - SVG Usage Documentation

src/app/ui-components/molecules/jumbotrons/jumbotrons.component.html, src/examples/jumbotron-combo/combo-video.js, src/examples/jumbotron-combo/index.html, src/examples/jumbotron-combo/manifest.json
Per Adam George's request, an example for how to combine inline and
background video jumbotrons has been added as part of this PR.
=> DE4324 Add inline and bg video combo example

package-lock.json, package.json
=> US9480 - Input Addon Focus

package.json, src/app/app.module.ts, src/app/shared/example/example.component.html, src/app/shared/example/example.component.spec.ts, src/app/shared/example/example.component.ts, src/app/shared/example/example.module.ts, src/styles/_examples.scss
Given a developer
When trying to utilize the markup within the DDK
Then I should be able to copy the sample markup via a simple button and copy it
=> US9476 - Code Copy Icon

src/app/ui-components/atoms/forms/search/search.component.html
Fix height of non-addon searchbar input.
crdschurch/crds-styles#229
crdschurch/crds-connect#752
=> DE4440 - Mobile searchbar height

src/app/ui-components/atoms/buttons/groups/groups.component.html
add CSS and HTML for new switch toggle style
Given a Crds designer/developer
When I need to implement a switch toggle button
Then I should find the styles for it within crds-styles and implementation information/markup within the DDK
https://projects.invisionapp.com/share/VRAO3U5ST#/screens/254126378_V2c-Filters
crdschurch/crds-styles#230
=> US10116 Add switch toggle to DDK

src/app/directives/icons/icons.service.ts, src/app/shared/example/example.component.html, src/styles/_examples.scss
Related to crdschurch/crds-styles#231
=> DE4478 copy icon

package-lock.json, package.json
Bump crds-styles to latest version. 
---
Related to... 
* crdschurch/crds-shared-header#95
* crdschurch/crds-connect#767
* crdschurch/crds-maestro#256
=> US10318 Publish NPM

src/index.html
Add crds-status-message to DDK
=> DE4539 Violator

package-lock.json, package.json
Tie styles dependency to upstream
=> US10116 Switch Toggle

config/webpack.common.js, config/webpack.test.js, package-lock.json, package.json, src/app/layout/footer/footer.component.html, src/app/layout/footer/footer.component.ts
Automate version number and timestamp in the DDK footer.
=> US9478 Version Number

src/index.html
Bump version of crds-status-message, pull config from S3
--- 
Related PRs:
https://github.com/crdschurch/crds-maestro/pull/281
https://github.com/crdschurch/crds-static/pull/14
=> US10573 Browser Support

package.json
=> US10660 - NPM Package

src/app/ui-components/core/utilities/images/images.component.html
Add utility instructions for aligning the background image to the top.
Corresponds with crdschurch/crds-styles#249
=> DE4675 - Bg img helper class

package-lock.json, package.json
Bump crds-styles to latest version
---
Related PRs...
crdschurch/crds-angular#4551
crdschurch/crds-maestro#305
=> US10830 crds-styles

package.json
=> US10937 - Release NPM Package

package.json
=> DEXXXX - update styles

src/index.html
Bump crds-status-message version
=> US10707 - Add CRDS Styles to Violator

src/app/ui-components/atoms/forms/checkboxes/checkboxes.component.html, src/app/ui-components/atoms/forms/nested-forms/nested-forms.component.html, src/app/ui-components/atoms/forms/radios/radios.component.html, src/app/ui-components/atoms/forms/toggles/toggles.component.html
Update example markup so it doesn't compile all those angular goodies.
No corresponding PRs.
=> DE4770 - Fix example code

src/app/ui-components/atoms/tooltips/tooltips.component.html, src/examples/tooltips/component.html
Fixes mobile behavior on tooltip on link
Corresponds to https://github.com/crdschurch/SS-CMS/pull/464
=> US11064 - Add Tooltips DDK

package.json
=> US11430 NPM Publish

src/app/ui-components/molecules/accordion/accordion.component.html
updates documentation copy for Accordion molecule
=> DE4803 - Fix copy in DDK for Accordion

src/index.html
Bump version of crds-status-message
=> DE4813 Close Button

src/app/ui-components/atoms/icons/inline-svg/inline-svg.component.html
Remove reference to webpack
---
Corresponds to crdschurch/crds-styles#270.
=> US11636 - Angular CLI Documentation

src/styles/_examples.scss, src/styles/_variables.scss
Fix backgrounds on interactive examples so they work well with non-interactive examples and so they mesh decently well with the dark theme.
=> DE4831 - chart example background

src/app/layout/header/header.component.html, src/app/ui-components/molecules/molecules-routing.module.ts, src/app/ui-components/molecules/molecules.module.ts, src/app/ui-components/molecules/sticky/sticky.component.html, src/app/ui-components/molecules/sticky/sticky.component.spec.ts, src/app/ui-components/molecules/sticky/sticky.component.ts, src/styles/_component-list.scss
Implementation & documentation on how to apply sticky header to pages
Links to https://github.com/crdschurch/crds-styles/pull/273
and https://github.com/crdschurch/SS-CMS/pull/472
=>  US11791 Add sticky header to DDK 

src/styles/_header.scss
Ensure active nav items are visible when viewing DDK through the dark-theme lens.
=> DE4939 Active Nav Items / Dark Theme

src/app/ui-components/molecules/cards/types/types.component.html
See crdschurch/crds-styles#283 and crdschurch/SS-CMS#491 for details.
=> US10242 - Schedule Content Block on Live

src/app/ui-components/core/colors/text/text.component.html
Adds documentation for .text-gray-light
Linked to: https://github.com/crdschurch/crds-styles/pull/285
And: https://github.com/crdschurch/crds-maestro/pull/413
=> US10248 - Implement Ways to Watch & Create community content blocks

package-lock.json, package.json
Pointing to dev branch of styles.
=> US11789 - ddk modals

src/app/ui-components/molecules/cards/card-decks/card-decks.component.html, src/examples/card-deck-carousel/index.html, src/examples/card-deck-default/index.html
Fix errors and missing info in carousel documentation
=> DE4985 - Fix Card Carousel Documentation

src/app/ui-components/core/utilities/images/images.component.html, src/app/ui-components/molecules/media-objects/media-objects.component.html
adds .img-border class for media objects
Linked to: https://github.com/crdschurch/crds-styles/pull/290
=> US10240 live Connect content block

package-lock.json, package.json
=> US12312 - Release styles

package.json, src/app/ui-components/molecules/countdown/countdown.component.html
Updated docs to support refactoring the countdown timer.
Corresponds with crdschurch/crds-styles#298.
=> DE4988 - Countdown on Live Jumbotron

package.json
=> US12713 - Release v2.3.0

package-lock.json, package.json, src/app/ui-components/molecules/cards/grid-layout/grid-layout.component.html
Normalize card image heights to 200px.
See note on crdschurch/crds-styles#303 for more context.
=> US12329 - Card Image Height

package-lock.json, package.json
=> US12884 - Update version

package-lock.json, package.json, src/app/ui-components/core/utilities/text/text.component.html
Add text shadow utility class documentation to DDK.
Corresponds with PR crdschurch/crds-styles#306
=> US12977 - Text shadow

src/examples/accordion/config.js, src/examples/button-dropdown/config.js, src/examples/charts/config.js, src/examples/datepicker/config.js, src/examples/default-modals/config.js, src/examples/fullscreen-modals/config.js, src/examples/map/config.js, src/examples/timepicker/config.js, src/examples/toastr/config.js, src/examples/tooltips/config.js
Specify version number for rxjs
=> DE5394 Interactive Examples

package-lock.json, package.json, src/app/ui-components/molecules/cards/grid-layout/grid-layout.component.html
Updates card grid documentation
Corresponds to https://github.com/crdschurch/crds-styles/pull/315
=> US13752 Series detail landing page

package-lock.json, src/app/ui-components/atoms/labels/labels.component.html, src/app/ui-components/core/utilities/borders/borders.component.html
Label documentation is missing info letting users know they can use utility classes with components.
Add documentation for labels and utilities.
Corresponds with crdschurch/crds-styles#316
=> US13828 - Labels

package-lock.json, package.json, src/app/directives/icons/icons.service.ts
=> US13811 - Featured Content

package-lock.json, package.json, src/app/directives/icons/icons.service.ts
Point styles to `#development` and add credit card and university icons to icon directory.
Corresponds with crdschurch/crds-styles#326
=> US14789 - Update icons

404.html, _includes/_header.html
Navigate to a 404 page and the CR logo does not show up.
Fix the path to the SVG.
=> Fix path to CR logo in header.

_assets/javascripts/application_deferred.js, _assets/javascripts/components/dark-theme.js, _includes/_header.html
Problem: No Dark Theme Toggle
Solution: Add working Dark Theme Toggle
=> DE5874 Dark Theme Toggle

_assets/javascripts/components/modal-example.js, ui-components/molecules/modals.html
Video on video modal continues playing when modal is closed.
Add JS to stop video when modal closes.
`/ui-components/molecules/modals`
=> DE5918 - Video modal

_redirects
Write redirects for INT and DEMO to point at PROD.
=> US15276 - Netlify redirects

Gemfile, Gemfile.lock, _includes/_header.html, _redirects, content-administrators/copy-voice.html, content-administrators/monetate-templates.html
Create a new nav cat for content admins and move copy/voice page to this section. Also add Monetate templates.
Corresponds with Corresponds with crdschurch/crds-styles#343
=> US15213 - CTA Templates

.gitmodules, Gemfile, Gemfile.lock, README.md, _assets/stylesheets/_example.scss, content-administrators/copy-voice.html, content-administrators/monetate-templates.html
Update Monetate Examples to include examples and styles for `.l-mini`
Update https://design.crossroads.net/content-administrators/monetate-templates
No corresponding PRs
https://deploy-preview-385--crds-styleguide.netlify.com/content-administrators/monetate-templates
=> US15978 additional monetate examples

_plugins/generators/icon_generator.rb, _plugins/hooks/icon_hook.rb, ui-components/atoms/icons/directory.html
Add hook & generator for dynamically populating the icon library
=> US16166 Icon Library

ui-components/core/colors/text.html
Adds documentation for new text color class
https://github.com/crdschurch/crds-media/pull/511
https://github.com/crdschurch/crds-styles/pull/373
https://deploy-preview-402--crds-styleguide.netlify.com/ui-components/core/colors/text
=> US16403 Article Subscribe CTA

index.html
=> de6470 broken link

.gitignore, Gemfile, Gemfile.lock, bin/netlify-redirector, netlify.toml, package-lock.json, package.json, redirects.csv
7-29-2020 - Olga's notes (sent them to Silas in slack). Can not access UI components to test in INT.
I tried getting here - https://crds-styleguide-int.netlify.app/ui-components/atoms/buttons, but got oops page. Netlify's preview works (https://deploy-preview-413--crds-styleguide-int.netlify.app/ui-components/atoms/buttons/component), but INT does not.
Actually it looks like clicking on anything under UI Components gets me the oops page.  FYI- I was able to access many UI components earlier today. So, I am moving your story back to Dev.
Fix redirects
=> US19868 Crds Button
